languages:
  JavaScript: true
exclude_paths:
  - "public/js/bluebird.min.js"
  - "public/js/bootstrap.js"
  - "public/js/bootstrap.min.js"
  - "public/js/ejs-2.3.1.js"
  - "public/js/ejs-2.3.1.min.js"
  - "public/js/jquery-2.1.4.min.js"
  - "public/js/leaflet.js"
  - "public/js/masonry.pkgd.min.js"
  - "public/js/moment.min.js"
  - "public/js/require.js"
  - "public/js/underscore-min.js"
