languages:
  JavaScript: true
exclude_paths:
  - "public/js/bluebird.min.js"
  - "public/js/ejs-1.0.0.js"
  - "public/js/ejs-1.0.0.min.js"
  - "public/js/jquery-2.1.4.min.js"
  - "public/js/underscore-min.js"
  - "public/js/underscore-min.map"
  - "public/js/leaflet.js"
  - "public/js/bootstrap.js"
  - "public/js/bootstrap.min.js"